pipeline:
# Create a new field using the gotemplate generator
- name: new-field
  gotemplate:
    # User defined inputs
    refVars:
      field:
        var: field
      value:
        var: value
    template:
      value:
        "{{ .field }}": "{{ .value }}"
- name: add-field
  merge:
    input:
      # We expect the input to this transformer to be provided externally,
      # rather than through another pipeline stage
      - var: input-object
      - ref: new-field
