pipeline:
# Create a new annotation using the gotemplate generator
- name: new-annotation
  gotemplate:
    # User defined inputs
    vars:
      annotation:
        var: annotation
      annotation_value:
        var: value
    template:
      value:
        metadata:
          annotations:
            "{{ .annotation }}": "{{ .annotation_value }}"
- name: add-annotation
  merge:
    input:
      # We expect the input to this transformer to be provided externally,
      # rather than through another pipeline stage
      - var: input-object
      - ref: new-annotation
