pipeline:
- name: add-field
  transformer:
    merge:
      input:
        # We expect the input to this transformer to be provided externally,
        # rather than through another pipeline stage
        - var: transformer-input
        - literal:
            new_field: some-value
- name: output
  output:
    yaml:
      input:
        - ref: add-field

