pipeline:
- name: helm
  pipeline:
    import:
      file: helm.yfg.yaml

# Only return the resources rendered by helm where kind is CustomResourceDefinition
- name: filter
  cel:
    input:
      ref: helm
      format: "yaml"
    expr: |
      // Need Check kind field exists, some empty YAML documents get output from helm template
      has(val.kind) && val.kind == "CustomResourceDefinition"
    filter: true
    # invertFilter: true
