pipeline:
- name: simple-exec
  exec:
    command: '/bin/bash'
    args: ['-c', 'echo {"foo": {"bar": "asdf hjkl"}}']

# Render the result as YAML
- name: output
  yaml:
    input:
      - ref: simple-exec

