pipeline:
- name: helm
  helm:
    chart: oci://public.ecr.aws/karpenter/karpenter
    version: 1.0.0
    releaseName: karpenter
    namespace: karpenter
    values:
      - value:
          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: karpenter-role
          settings:
            clusterName: my-eks-cluster
            clusterEndpoint: https://1234567890ABCDEF1234567890ABCDEF.xx0.region.eks.amazonaws.com
            interruptionQueue: my-eks-cluster
