pipeline:
# convert to JSON for JQ
- name: json
  json:
    input:
      - file: files/service.yaml
- name: jq
  jq:
    expr: '{metricsPort: (.spec.ports[] | select(.name=="metrics") | .port)}'
    input:
      ref: json
- name: yaml
  yaml:
    input:
      - ref: jq
