pipeline:
- name: service
  file:
    path: files/service.yaml
# convert to JSON for JQ
- name: json
  json:
    input:
      - ref: service
- name: jq
  jq:
    expr: '{metricsPort: (.spec.ports[] | select(.name=="metrics") | .port)}'
    input:
      ref: json
- name: yaml
  yaml:
    input:
      - ref: jq
