pipeline:
# convert to JSON for JSON patch
- name: json
  json:
    input:
      - file: files/service.yaml
- name: patch
  jsonpatch:
    patch: |
      apiVersion: v1
      kind: Service
      metadata:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
    merge: true
    input:
      ref: json
- name: yaml
  yaml:
    input:
      - ref: patch
