pipeline:
# convert to JSON for JSON patch
- name: json
  json:
    input:
      - file: files/service.yaml
- name: patch
  jsonpatch:
    patch: |
      [
        {"op": "add", "path": "/metadata/annotations/service.beta.kubernetes.io~1aws-load-balancer-type", "value": "nlb"}
      ]
    input:
      ref: json
- name: yaml
  yaml:
    input:
      - ref: patch
