pipeline:
- name: simple-exec
  exec:
    command: '/bin/bash'
    args: ['-c', 'echo {"foo": {"bar": "asdf hjkl"}}']

- name: simple-file
  file:
    path: files/test.yaml

- name: merged
  merge:
    input:
      - ref: simple-file
      - ref: simple-exec
