pipeline:
- name: service
  file:
    path: files/service.yaml

- name: k8s-namespace
  yaml:
    input:
      - value:
          metadata:
            namespace: example

- name: merged
  merge:
    input:
      - ref: service
      - ref: k8s-namespace
