pipeline:
- name: k8s-namespace
  yaml:
    input:
      - value:
          metadata:
            namespace: example

- name: merged
  merge:
    input:
      - file: files/service.yaml
      - ref: k8s-namespace
