pipeline:
- name: template
  gotemplate:
    template: |
      server {
          listen {{ .listenAddress }};
          root {{ .webRoot }};

          location / {
          }
      }
    vars:
      listenAddress: 8080
      webRoot: /var/www/data
