pipeline:
- name: template
  gotemplate:
    template:
      value: |
        server {
            listen {{ .listenAddress }};
            root {{ .webRoot }};

            location / {
            }
        }
    vars:
      listenAddress: 8080
      webRoot: /var/www/data
