pipeline:
- name: karpenter-values
  gotemplate:
    vars:
      eks:
        file: ../files/eks-vars.yaml
        format: yaml
    template:
      value:
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: "{{ .eks.roleARN }}"
        settings:
          clusterName: "{{ .eks.clusterName }}"
          clusterEndpoint: "{{ .eks.clusterEndpoint }}"
          interruptionQueue: "{{ .eks.clusterName }}"

- name: helm
  helm:
    chart: oci://public.ecr.aws/karpenter/karpenter
    version: 1.0.0
    releaseName: karpenter
    namespace: karpenter
    includeCRDs: true
    values:
      - ref: karpenter-values
