# Generators can be re-used.
# The generator defined in transformers/add-field will add the new field based
# on vars provided.
pipeline:
# You can import other generators for re-use.
- name: add-field
  pipeline:
    import:
      file: ../transformers/add-annotation.yaml
    vars:
      # We're passing the output of the -file stage as the
      # transformer-input var in the add-field transformer
      - name: input-object
        file: ../files/service.yaml
      # The add-field generator takes an input variable "field" as the field to
      # add
      - name: annotation
        value: "service.beta.kubernetes.io/aws-load-balancer-type"
      # The add-field generator takes an input variable "value" as the value of
      # the field to add
      - name: value
        value: "nlb"
