name: Create a release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Generate artifacts
        run: make release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: 'yfg-*'
